# Generated by Django 5.1.4 on 2025-01-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_categoria_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=10, help_text='Digite o preço do produto.', max_digits=10, verbose_name='Preço do Produto'),
        ),
    ]
