# Generated by Django 5.1.4 on 2025-02-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=10, help_text='Digite o preço do produto.', max_digits=10, verbose_name='Preço do Produto'),
        ),
    ]
